# Generated by Django 5.1.1 on 2026-04-30 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа квеста', max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание типа квеста', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'тип квеста',
                'verbose_name_plural': 'Типы квестов',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название квеста', max_length=150, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание квеста', verbose_name='Описание')),
                ('min_level', models.PositiveSmallIntegerField(help_text='Уровень доступа для персонажа (только для авантюристов)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Уровень')),
                ('reward', models.CharField(help_text='Награда за выполнение квеста', max_length=128, verbose_name='Награда')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='available', help_text='Текущий статус квеста', max_length=11, verbose_name='Статус')),
                ('monster', models.CharField(help_text='Монстр для квеста', max_length=128, verbose_name='Монстр')),
                ('adventurer', models.ForeignKey(blank=True, help_text='Исполнитель квеста', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_quests', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('quest_type', models.ForeignKey(help_text='Тип для квеста', on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='quests.questtype', verbose_name='Тип квеста')),
            ],
            options={
                'verbose_name': 'квест',
                'verbose_name_plural': 'Квесты',
            },
        ),
        migrations.CreateModel(
            name='QuestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], help_text='Результат выполнения квеста', max_length=7, verbose_name='Результат')),
                ('comment', models.TextField(help_text='Комментарий авантюриста', verbose_name='Комментарий')),
                ('adventurer', models.ForeignKey(help_text='Автор отчета', on_delete=django.db.models.deletion.CASCADE, related_name='quest_reports', to=settings.AUTH_USER_MODEL, verbose_name='Авантюрист')),
                ('quest', models.ForeignKey(help_text='Отчет к квесту', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='quests.quest', verbose_name='Квест')),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
